global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: receiver@mail.com
    from: sender@mail.com
    smarthost: smtp.gmail.com:587
    auth_username: sender@mail.com
    auth_identity: sender@mail.com
    auth_password: pfwpvitpyeqigorr
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']